=== Vishali-Moorthy/XmlFiles/Employee.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">
<xs:element name="employee">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="empno" type="xs:integer"/>
			<xs:element name="empname" type="xs:string"/>
			<xs:element name="salary" type="xs:salary"/>
			<xs:element name="band" type="xs:string"/>
			<xs:element name="date" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== Vishali-Moorthy/XmlFiles/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Employee.xsd">
<employeedata>
	<employee>
		<empno>1</empno>
		<empname>Visha</empname>
		<salary>24300</salary>
		<band>C</band>
		<date>2019-11-06</date>
	</employee>
	<employee>
		<empno>2</empno>
		<empname>Sambavi</empname>
		<salary>21000</salary>
		<band>E</band>
		<date>2009-01-16</date>
	</employee>
	<employee>
		<empno>3</empno>
		<empname>Moni</empname>
		<salary>37900</salary>
                <band>M</band>
		<date>2012-08-03</date>
	</employee>
</employeedata>
